name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github

      - name: Run Laravel Pint (Code Style)
        run: ./vendor/bin/pint --test

      - name: Run Tests
        run: ./vendor/bin/pest

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Run tests with coverage
        run: ./vendor/bin/pest --coverage --min=80

  compatibility:
    name: PHP Compatibility Matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Run tests
        run: ./vendor/bin/pest