name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Make build scripts executable
        run: chmod +x build/*.sh

      - name: Update changelog with our build system
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          echo "Updating changelog for released version: $VERSION"
          
          # Only update if this version isn't already in the changelog
          if ! grep -q "## \[${VERSION}\]" CHANGELOG.md; then
            bash build/update-changelog.sh "$VERSION"
          else
            echo "Version $VERSION already exists in changelog, skipping update"
          fi

      - name: Commit updated CHANGELOG
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          if git diff --quiet CHANGELOG.md; then
            echo "No changelog changes to commit"
          else
            git add CHANGELOG.md
            git commit -m "Update CHANGELOG.md for released version $VERSION

            🤖 Generated with [Claude Code](https://claude.ai/code)

            Co-Authored-By: Claude <noreply@anthropic.com>"
            git push origin main
          fi
